apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mockbin-apps-example-com-certificate
  namespace: cert-manager-operator
spec:
  commonName: Mockbin Geo use-case certificate
  dnsNames:
    - mockbin.apps.example.com
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: example-intermediate-central-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: mockbin-apps-example-com-certificate
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
  subject:
    countries:
      - US
    organizationalUnits:
      - Use-Case Geo based Locality LoadBalancing
    organizations:
      - Example
