apiVersion: v1
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: cert-manager-operator/apps-example-com-wildcard-certificate
  name: gateway-secret
type: kubernetes.io/tls
---
