apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yml
- destinationrule.yml
- gateway-deploy.yml
- gateway-rbac.yml
- gateway-service.yml
- gateway.yml
- service.yml
- virtualservice.yml
- route.yml

images:
- name: localhost/mockbin
  newName: ghcr.io/michaelalang/mockbin
  newTag: v1.0.0
